version: '3'

services:
  elasticsearch:
    container_name: cont_elastic
    image: elasticsearch:7.17.7
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elk_data:/usr/share/elasticsearch/data
