ARG ELK_VERSION

# Get image from Docker Hub
FROM elastic/metricbeat:${ELK_VERSION}

# Get image from https://www.docker.elastic.co/
#FROM docker.elastic.co/beats/metricbeat:${ELK_VERSION}

# Change file permission for docker module monitoring